# Generated by Django 5.1.4 on 2024-12-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frognet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=123, max_length=200, verbose_name='Название поста'),
            preserve_default=False,
        ),
    ]
