# Generated by Django 5.1.4 on 2025-01-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frognet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
