# Generated by Django 5.1.4 on 2025-01-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='baner',
            field=models.ImageField(blank=True, default='5.jpg', upload_to='images', verbose_name='Банер профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='iamges', verbose_name='Профиль'),
        ),
    ]
